# Generated using prebuild.py
from typing import TypeAlias, Literal
abilityLocation: TypeAlias = Literal[
"Sun Cavern - Sage's Blessing 1",
"Sun Cavern - Sage's Blessing 2",
"Sun Cavern - Sage's Blessing 3",
"Sun Cavern - Sage's Blessing 4",
"Sun Cavern - Sage's Blessing 5",
]
abilityItem: TypeAlias = Literal[
"Tail",
"Horn",
"Wings",
"Bubble",
"Flight",
]
nonVanillaAbilityItem: TypeAlias = Literal[
"Grounded Tail",
"Aerial Tail",
"Double Jump",
"Roll",
"Swim",
"Carry",
"Climb",
"High Jump",
"Sprint",
"Super Jumps",
"Air Swim",
]
pickupLocation: TypeAlias = Literal[
"Lostleaf Lake - Treehouse Fish Food",
"Lady Opal's Egg: Castle",
"Lady Opal's Egg: Pool",
"Lady Opal's Egg: Poki-Poki",
]
pickupItem: TypeAlias = Literal[
"Fish Food",
"Lady Opal's Egg 1",
"Lady Opal's Egg 2",
"Lady Opal's Egg 3",
]
eventLocation: TypeAlias = Literal[
"Beat Mighty Wall",
"Moon Cavern Heart Door",
"Armada Lobby Purple Valve",
"Armada Lobby Green Valve",
"Palace Lobby Faucet Preston",
"Palace Lobby Whirlpool Preston",
"Gallery Lobby - Extinguish Torches",
"Gallery Lobby - Hedge Maze Preston",
"Lostleaf Lake - Winky Tree Target",
"Lostleaf Lake - Help Shelnert",
"Lostleaf Lake - Back of the Headstone",
"Lostleaf Lake - Ring Bell",
"Lostleaf Lake - Angel Statue Puzzle",
"Lostleaf Lake - Treehouse Preston",
"Armada Interior - Help Mr. Kerrington",
"Armada Interior - Generators Puzzle",
"Heart - Generators Puzzle",
"Prismic Palace - Basement Star Hoops",
"Palace-Lostleaf Connector - Preston",
"Prismic Palace - Angel Statue Puzzle",
"Prismic Palace - Help Lady Opal",
"Prismic Palace - Snowcastle Preston",
"Prismic Palace - Observatory Preston",
"Palace Interior - Sentry Control Preston",
"Palace Interior - Seastar Puzzle",
"Heaven's Path - Finished Race",
"Heaven's Path - Bottom Preston",
"Palace Dining Room - Preston",
"Gallery of Nightmares - Sage's Painting",
"Gallery of Nightmares - Mr. Kerrington's Painting",
"Gallery of Nightmares - Shelnert's Painting",
"Gallery-Armada Connector - Preston",
"Gallery of Nightmares - Swamp Angel Statue Puzzle",
"Gallery of Nightmares - Sewer Angel Statue Puzzle",
"Gallery of Nightmares - Lady Opal's Painting",
"Gallery of Nightmares - Helped Sniffles",
"Gallery of Nightmares - Fire Lobby Preston",
"Gallery of Nightmares - Fire Lobby Hoops",
"Coils of Agony - Hidden Pillar",
]
eventItem: TypeAlias = Literal[
"Mighty Wall Toppled",
"Open Moon Cavern Heart Door",
"Armada Lobby Pipes Risen",
"Armada Lobby Red Pipe Updraft",
"Palace Lobby Faucet Running",
"Palace Lobby Whirlpool Active",
"Open Gallery Lobby Hedge Maze",
"Open Gallery Lobby Door",
"Raise Lake Swings",
"Open Deep Woods",
"Open Crypt",
"Open Church",
"Open Church Egg",
"Open Treehouse",
"Open Armada Cockpit",
"Free Armada Buddies",
"Unclog Kerrington's Heart",
"Open Prismic Palace Basement",
"Open Palace-Lostleaf Connector",
"Open Prismic Palace Gate",
"Unfreeze Prismic Palace",
"Open Prismic Palace Snowcastle",
"Open Observatory Shortcut",
"Disable Prismic Palace Seedragons",
"Open Bubble Conch Room",
"Open Heaven's Path Exit",
"Open Heaven's Path Race Entrance",
"Raise Dining Room Platform",
"Open Gallery Doors",
"Open Mr. Kerrington Painting Gate",
"Open Skull's Diamond Eye",
"Open Gallery-Armada Connector",
"Open Gallery of Nightmares Swamp Door",
"Open Gallery of Nightmares Sewer Chest #1",
"Open Gallery of Nightmares Sewer Chest #2",
"Open Luna's House",
"Extend Fire Lobby Tongue Platform",
"Extend Fire Lobby Frying Pans",
"Coils of Agony - Open Snake's Mouth",
]
cardLocation: TypeAlias = Literal[
"Card: Sun Cavern - Air Vent",
"Card: Lostleaf Lobby - Branches",
"Card: Moon Cavern - Statue",
"Card: Armada Lobby - Jester Boots",
"Card: Moon Cavern - Dive",
"Card: Gallery Lobby - Hedge Maze",
"Card: Lostleaf Lake - Teepee",
"Card: Lostleaf Lake - Apple Tree",
"Card: Lostleaf Lake - Lake Stump",
"Card: Church - Top",
"Card: Lostleaf Lake - Entry",
"Card: Lostleaf Lake - Treehouse",
"Card: Armada Interior - Slide",
"Card: Armada Interior - Pipe",
"Card: Armada Interior - Broken Wing",
"Card: Airborne Armada - Behind Entry Drone",
"Card: Armada Interior - Hammocks",
"Card: Armada Interior - Near Mr. Kerrington's Heart",
"Card: Prismic Palace - Observatory",
"Card: Prismic Palace - Top of Observatory",
"Card: Prismic Palace - Snowcastle",
"Card: Prismic Palace - Top of Palace",
"Card: Prismic Palace - Above Pool",
"Card: Prismic Palace - Inside Palace",
"Card: Gallery of Nightmares - Swamp Castle",
"Card: Gallery of Nightmares - Sewer Bottom",
"Card: Gallery of Nightmares - Basement Entrance",
"Card: Gallery of Nightmares - Swamp",
"Card: Gallery of Nightmares - Frying Pans",
"Card: Gallery of Nightmares - Above Pits of Despair Painting",
"Card: Sewer - Armada Lobby Side",
"Card: Sewer - Gallery of Nightmares Side",
"Card: Dream",
"Card: Gallery Lobby - Behind the Gallery",
"Card: Palace Dining Room - Top",
"Card: Palace Lobby - Top",
]
cardItem: TypeAlias = Literal[
"Card: Shroom",
"Card: Mighty Wall",
"Card: Pale Carpy",
"Card: Preston",
"Card: Keehee",
"Card: Hunger",
"Card: Shelnert",
"Card: Shelwart",
"Card: Carpy",
"Card: Raay",
"Card: Sappleing",
"Card: Gabby Grove",
"Card: Mr. Kerrington",
"Card: Skritch",
"Card: Boiby",
"Card: Dumpling",
"Card: F.I.S.H",
"Card: Reaper",
"Card: Lady Opal",
"Card: Poki-Poki",
"Card: Pom",
"Card: Bigstar",
"Card: The Gobbler!",
"Card: Seedragon",
"Card: Rattles",
"Card: Sniffles",
"Card: Starving Art",
"Card: Eternal",
"Card: Heartburn",
"Card: Hawhaw",
"Card: Fynn",
"Card: Fynn's Siblings",
"Card: Sage",
"Card: Luna",
"Card: Boxed Nightmare",
"Card: Frozen King",
]
eggLocation: TypeAlias = Literal[
"Egg: Sun Cavern - Mighty Wall",
"Egg: Sun Cavern - Waterfall",
"Egg: Moon Cavern - Dive Puzzle",
"Egg: Moon Cavern - Keehee Climb",
"Egg: Lostleaf Lobby - Branches",
"Egg: Armada Lobby - Cannon",
"Egg: Palace Lobby - Submerged",
"Egg: Gallery Lobby - Lostleaf Lobby Entryway",
"Egg: Lostleaf Lake - Entry Stump",
"Egg: Lostleaf Lake - Jester Boots",
"Egg: Lostleaf Lake - Lake Log",
"Egg: Lostleaf Lake - Waterfall",
"Egg: Crypt - Shelwart's Gravestone",
"Egg: Lostleaf Lake - Deep Woods Puzzle",
"Egg: Lostleaf Lake - Near the Treehouse",
"Egg: Church - Below the Angel Statues",
"Egg: Airborne Armada - Mr. Kerrington's Tail",
"Egg: Fire Drone",
"Egg: Armada Interior - Slide",
"Egg: Armada Interior - Dog Food",
"Egg: Armada Interior - Boiler",
"Egg: Armada Interior - Pipe",
"Egg: Mr. Kerrington's Heart",
"Egg: Armada Interior - Dumpling",
"Egg: Prismic Palace - Snowcastle",
"Egg: Palace Dining Room",
"Egg: Observatory",
"Egg: Prismic Palace - Observatory Slide",
"Egg: Prismic Palace - Bigstar",
"Egg: Prismic Palace - Top of the Palace",
"Egg: Palace Interior - Basement",
"Egg: Prismic Palace - Gobbler",
"Egg: Coils of Agony",
"Egg: Pits of Despair",
"Egg: Wastes of Eternity",
"Egg: Gallery of Nightmares - Matryoshka Egg",
"Egg: Gallery of Nightmares - Skull's Eye",
"Egg: Gallery of Nightmares - Mr. Kerrington Painting",
"Egg: Gallery of Nightmares - Sewer",
"Egg: Gallery of Nightmares - Deepest Darkness",
]
eggItem: TypeAlias = Literal[
"Sun Egg",
"Green Starry Egg",
"Blue Moon Egg",
"Blorange Striped Egg",
"Blue Dotted Egg",
"American Egg",
"Red Swirly Egg",
"Ghost Egg",
"Hatchable Egg: Lostleaf Lake",
"Easter Zig-zag Egg",
"Apple Egg",
"Snowfall Egg",
"Fishbones Egg",
"Sunshine Egg",
"Birds Egg",
"Stained Glass Egg",
"Hatchable Egg: Airborne Armada",
"Burning Egg",
"Bat Egg",
"Doggy Egg",
"Spooky Egg",
"Smiley Egg",
"Heart Egg",
"Dumpling Egg",
"Hatchable Egg: Prismic Palace",
"Ornate Egg",
"Starlit Egg",
"Checkered Egg",
"Flower Egg",
"Snowstorm Egg",
"Zig-zag Egg",
"Happy Egg",
"Red Eyes Egg",
"Seaweed Egg",
"Moonlight Egg",
"Hatchable Egg: Gallery of Nightmares",
"Ripped Egg",
"Robot Egg",
"Bricked Egg",
"Ghost Egg",
]
shroomLocation: TypeAlias = Literal[
"Shroom: Sun Cavern - Mighty Wall Ground 1",
"Shroom: Sun Cavern - Mighty Wall Ground 2",
"Shroom: Sun Cavern - Mighty Wall Ground 3",
"Shroom: Sun Cavern - Mighty Wall Ground 4",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 1",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 2",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 3",
"Shroom: Sun Cavern - High Jump Ledge 1",
"Shroom: Sun Cavern - High Jump Ledge 2",
"Shroom: Sun Cavern - Tail Spin Ledge 1",
"Shroom: Sun Cavern - Tail Spin Ledge 2",
"Shroom: Sun Cavern - Ducklings Ledge 1",
"Shroom: Sun Cavern - Ducklings Ledge 2",
"Shroom: Sun Cavern - Armada Entrance 1",
"Shroom: Sun Cavern - Armada Entrance 2",
"Shroom: Sun Cavern - Armada Entrance 3",
"Shroom: Sun Cavern - Vine Ledge 1",
"Shroom: Sun Cavern - Vine Ledge 2",
"Shroom: Moon Cavern - Dive Holes 1",
"Shroom: Moon Cavern - Dive Holes 2",
"Shroom: Moon Cavern - Dive Holes 3",
"Shroom: Moon Cavern - Dive Holes 4",
"Shroom: Moon Cavern - Dive Holes 5",
"Shroom: Moon Cavern - Dive Holes 6",
"Shroom: Moon Cavern - Dive Puzzle 1",
"Shroom: Moon Cavern - Dive Puzzle 2",
"Shroom: Moon Cavern - Dive Puzzle 3",
"Shroom: Moon Cavern - Potionfall",
"Shroom: Moon Cavern - Lonely Shroom",
"Shroom: Moon Cavern - Palace Lobby Pathway 2",
"Shroom: Moon Cavern - Palace Lobby Pathway 1",
"Shroom: Moon Cavern - Palace Lobby Pathway 3",
"Shroom: Moon Cavern - Palace Lobby Statue 1",
"Shroom: Moon Cavern - Palace Lobby Statue 2",
"Shroom: Moon Cavern - Palace Lobby Entryway 1",
"Shroom: Moon Cavern - Palace Lobby Entryway 2",
"Shroom: Moon Cavern - Palace Lobby Entryway 3",
"Shroom: Moon Cavern - Lava Platforms 1",
"Shroom: Moon Cavern - Lava Platforms 2",
"Shroom: Moon Cavern - Lava Platforms 3",
"Shroom: Moon Cavern - Lava Platforms 4",
"Shroom: Moon Cavern - Lava Mushroom Platform 1",
"Shroom: Moon Cavern - Lava Mushroom Platform 2",
"Shroom: Lostleaf Lobby - Bridge 2",
"Shroom: Lostleaf Lobby - Bridge 3",
"Shroom: Lostleaf Lobby - Bridge 1",
"Shroom: Lostleaf Lobby - Trees 1",
"Shroom: Lostleaf Lobby - Trees 2",
"Shroom: Lostleaf Lobby - Trees 3",
"Shroom: Armada Lobby - Cliffside 1",
"Shroom: Armada Lobby - Cliffside 2",
"Shroom: Armada Lobby - Cliffside 4",
"Shroom: Armada Lobby - Cliffside 5",
"Shroom: Armada Lobby - Cliffside 3",
"Shroom: Palace Lobby - Ledges 1",
"Shroom: Palace Lobby - Ledges 6",
"Shroom: Palace Lobby - Ledges 5",
"Shroom: Palace Lobby - Ledges 3",
"Shroom: Palace Lobby - Ledges 2",
"Shroom: Palace Lobby - Ledges 4",
"Shroom: Palace Lobby - Underwater 1",
"Shroom: Palace Lobby - Underwater 2",
"Shroom: Palace Lobby - Underwater 3",
"Shroom: Palace Lobby - Underwater 5",
"Shroom: Palace Lobby - Underwater 6",
"Shroom: Palace Lobby - Underwater 4",
"Shroom: Gallery Lobby - Fountain 1",
"Shroom: Gallery Lobby - Fountain 2",
"Shroom: Gallery Lobby - Fountain 3",
"Shroom: Gallery Lobby - Fountain 4",
"Shroom: Gallery Lobby - Castle Hill 3",
"Shroom: Gallery Lobby - Castle Hill 5",
"Shroom: Gallery Lobby - Castle Hill 4",
"Shroom: Gallery Lobby - Castle Hill 1",
"Shroom: Gallery Lobby - Castle Hill 2",
"Shroom: Gallery Lobby - Entryway 1",
"Shroom: Gallery Lobby - Entryway 4",
"Shroom: Gallery Lobby - Entryway 5",
"Shroom: Gallery Lobby - Entryway 3",
"Shroom: Gallery Lobby - Entryway 2",
"Shroom: Lostleaf Lake - Treehouse Branches 4",
"Shroom: Lostleaf Lake - Treehouse Branches 3",
"Shroom: Lostleaf Lake - Treehouse Branches 1",
"Shroom: Lostleaf Lake - Treehouse Branches 2",
"Shroom: Lostleaf Lake - Treehouse Branches 6",
"Shroom: Lostleaf Lake - Treehouse Branches 5",
"Shroom: Lostleaf Lake - Deep Woods 2",
"Shroom: Lostleaf Lake - Deep Woods 1",
"Shroom: Lostleaf Lake - Deep Woods 3",
"Shroom: Lostleaf Lake - Deep Woods 6",
"Shroom: Lostleaf Lake - Deep Woods 4",
"Shroom: Lostleaf Lake - Deep Woods 5",
"Shroom: Lostleaf Lake - Behind Church 3",
"Shroom: Lostleaf Lake - Behind Church 1",
"Shroom: Lostleaf Lake - Behind Church 2",
"Shroom: Lostleaf Lake - Teepee 1",
"Shroom: Lostleaf Lake - Teepee 3",
"Shroom: Lostleaf Lake - Teepee 2",
"Shroom: Lostleaf Lake - Waterfall Logs 2",
"Shroom: Lostleaf Lake - Waterfall Logs 3",
"Shroom: Lostleaf Lake - Waterfall Logs 4",
"Shroom: Lostleaf Lake - Waterfall Logs 1",
"Shroom: Lostleaf Lake - Lake Logs 2",
"Shroom: Lostleaf Lake - Lake Logs 1",
"Shroom: Lostleaf Lake - Lake Logs 3",
"Shroom: Lostleaf Lake - Lake Logs 4",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 1",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 2",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 3",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 1",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 3",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 5",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 2",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 4",
"Shroom: Lostleaf Lake - Deep Woods Entryway 1",
"Shroom: Lostleaf Lake - Deep Woods Entryway 2",
"Shroom: Lostleaf Lake - Deep Woods Entryway 3",
"Shroom: Lostleaf Lake - Lake Gravestone 1",
"Shroom: Lostleaf Lake - Lake Gravestone 2",
"Shroom: Lostleaf Lake - Lake Gravestone 3",
"Shroom: Lostleaf Lake - Bridge 2",
"Shroom: Lostleaf Lake - Bridge 1",
"Shroom: Lostleaf Lake - Bridge 3",
"Shroom: Lostleaf Lake - Winky Apple Tree 4",
"Shroom: Lostleaf Lake - Winky Apple Tree 3",
"Shroom: Lostleaf Lake - Winky Apple Tree 1",
"Shroom: Lostleaf Lake - Winky Apple Tree 2",
"Shroom: Lostleaf Lake - Church Entryway 3",
"Shroom: Lostleaf Lake - Church Entryway 2",
"Shroom: Lostleaf Lake - Church Entryway 1",
"Shroom: Church - Pews 4",
"Shroom: Church - Pews 2",
"Shroom: Church - Pews 1",
"Shroom: Church - Pews 3",
"Shroom: Treehouse - Corners 4",
"Shroom: Treehouse - Corners 3",
"Shroom: Treehouse - Corners 2",
"Shroom: Treehouse - Corners 1",
"Shroom: Treehouse - Corners 5",
"Shroom: Treehouse - Corners 6",
"Shroom: Airborne Armada - Bouncy Shroom 1",
"Shroom: Airborne Armada - Bouncy Shroom 3",
"Shroom: Airborne Armada - Bouncy Shroom 2",
"Shroom: Airborne Armada - Bouncy Shroom 4",
"Shroom: Airborne Armada - Entry Pathway 5",
"Shroom: Airborne Armada - Front Entrance 1",
"Shroom: Airborne Armada - Front Entrance 2",
"Shroom: Airborne Armada - Front Entrance 3",
"Shroom: Airborne Armada - Side 1",
"Shroom: Airborne Armada - Side 2",
"Shroom: Airborne Armada - Side 3",
"Shroom: Airborne Armada - Back Entrance 1",
"Shroom: Airborne Armada - Back Entrance 2",
"Shroom: Airborne Armada - Back Entrance 3",
"Shroom: Airborne Armada - Back Entrance 4",
"Shroom: Airborne Armada - Back Entrance 6",
"Shroom: Airborne Armada - Back Entrance 5",
"Shroom: Airborne Armada - Topside 1",
"Shroom: Airborne Armada - Topside 2",
"Shroom: Airborne Armada - Topside 3",
"Shroom: Airborne Armada - Entry Pathway 1",
"Shroom: Airborne Armada - Entry Pathway 2",
"Shroom: Airborne Armada - Entry Pathway 3",
"Shroom: Airborne Armada - Entry Pathway 4",
"Shroom: Armada Interior - Rain Entryway 4",
"Shroom: Armada Interior - Rain Entryway 3",
"Shroom: Armada Interior - Rain Entryway 2",
"Shroom: Armada Interior - Hammocks Entryway 2",
"Shroom: Armada Interior - Hammocks Entryway 1",
"Shroom: Armada Interior - Cockpit Entry 3",
"Shroom: Armada Interior - Cockpit Entry 2",
"Shroom: Armada Interior - Cockpit Entry 1",
"Shroom: Armada Interior - Cockpit Entry 6",
"Shroom: Armada Interior - Cockpit Entry 5",
"Shroom: Armada Interior - Cockpit Entry 4",
"Shroom: Armada Interior - Rain Below Medicine 3",
"Shroom: Armada Interior - Rain Below Medicine 2",
"Shroom: Armada Interior - Rain Below Boiler 1",
"Shroom: Armada Interior - Rain Below Boiler 2",
"Shroom: Armada Interior - Rain Below Boiler 3",
"Shroom: Armada Interior - Rain Below Medicine 1",
"Shroom: Armada Interior - Rain Plant Base",
"Shroom: Armada Interior - Rain Plant 1",
"Shroom: Armada Interior - Lab Rain Connector 5",
"Shroom: Armada Interior - Lab Rain Connector 6",
"Shroom: Armada Interior - Lab Rain Connector 4",
"Shroom: Armada Interior - Lab Rain Connector 3",
"Shroom: Armada Interior - Lab Rain Connector 2",
"Shroom: Armada Interior - Lab Rain Connector 1",
"Shroom: Armada Interior - Lab Entryway 4",
"Shroom: Armada Interior - Lab Entryway 3",
"Shroom: Armada Interior - Lab Entryway 2",
"Shroom: Armada Interior - Lab Entryway 1",
"Shroom: Armada Interior - Pipe 5",
"Shroom: Armada Interior - Pipe 4",
"Shroom: Armada Interior - Pipe 3",
"Shroom: Armada Interior - Pipe 2",
"Shroom: Armada Interior - Pipe 1",
"Shroom: Armada Interior - Pipe Ramp 3",
"Shroom: Armada Interior - Pipe Ramp 2",
"Shroom: Armada Interior - Pipe Ramp 1",
"Shroom: Armada Interior - Rain Entryway 1",
"Shroom: Armada Interior - Slide Entryway 1",
"Shroom: Armada Interior - Slide Entryway 2",
"Shroom: Armada Interior - Slide Entryway 3",
"Shroom: Armada Interior - Rain Plant 2",
"Shroom: Armada Interior - Rain Plant 3",
"Shroom: Armada Interior - Rain Plant 4",
"Shroom: Armada Interior - Rain Above Boiler 4",
"Shroom: Armada Interior - Rain Above Boiler 2",
"Shroom: Armada Interior - Rain Above Boiler 1",
"Shroom: Armada Interior - Rain Above Boiler 3",
"Shroom: Armada Entry Drone - Ledges 6",
"Shroom: Armada Entry Drone - Ledges 5",
"Shroom: Armada Entry Drone - Ledges 4",
"Shroom: Armada Entry Drone - Ledges 3",
"Shroom: Armada Entry Drone - Ledges 7",
"Shroom: Armada Entry Drone - Ledges 8",
"Shroom: Armada Entry Drone - Ledges 1",
"Shroom: Armada Entry Drone - Ledges 2",
"Shroom: Prismic Palace - Poms 5",
"Shroom: Prismic Palace - Poms 3",
"Shroom: Prismic Palace - Poms 4",
"Shroom: Prismic Palace - Poms 2",
"Shroom: Prismic Palace - Poms 1",
"Shroom: Prismic Palace - Entry Tree 2",
"Shroom: Prismic Palace - Entry Tree 1",
"Shroom: Prismic Palace - Entry Tree 3",
"Shroom: Prismic Palace - Entry 1",
"Shroom: Prismic Palace - Entry 2",
"Shroom: Prismic Palace - Entry 3",
"Shroom: Prismic Palace - Jester Boots 1",
"Shroom: Prismic Palace - Jester Boots 2",
"Shroom: Prismic Palace - Jester Boots 3",
"Shroom: Prismic Palace - Jester Boots 4",
"Shroom: Prismic Palace - Jester Boots 5",
"Shroom: Prismic Palace - Pom Spire 1",
"Shroom: Prismic Palace - Pom Spire 2",
"Shroom: Prismic Palace - Pom Spire 3",
"Shroom: Prismic Palace - Pom Spire 4",
"Shroom: Prismic Palace - Pom Spire 5",
"Shroom: Prismic Palace - Observatory Spire 1",
"Shroom: Prismic Palace - Observatory Spire 2",
"Shroom: Prismic Palace - Observatory Spire 3",
"Shroom: Prismic Palace - Observatory Spire 4",
"Shroom: Prismic Palace - Observatory Spire 5",
"Shroom: Prismic Palace - Lake Gobbler 2",
"Shroom: Prismic Palace - Lake Gobbler 3",
"Shroom: Prismic Palace - Lake Gobbler 1",
"Shroom: Prismic Palace - Lake Plants 2",
"Shroom: Prismic Palace - Lake Plants 3",
"Shroom: Prismic Palace - Lake Plants 1",
"Shroom: Prismic Palace - Lake Plants 5",
"Shroom: Prismic Palace - Lake Plants 6",
"Shroom: Prismic Palace - Lake Plants 4",
"Shroom: Prismic Palace - Lake Basement Overpass 3",
"Shroom: Prismic Palace - Lake Basement Overpass 4",
"Shroom: Prismic Palace - Lake Basement Overpass 5",
"Shroom: Prismic Palace - Lake Basement Overpass 2",
"Shroom: Prismic Palace - Lake Basement Overpass 1",
"Shroom: Prismic Palace - Lake Mushroom Cave 3",
"Shroom: Prismic Palace - Lake Mushroom Cave 4",
"Shroom: Prismic Palace - Lake Mushroom Cave 5",
"Shroom: Prismic Palace - Lake Mushroom Cave 2",
"Shroom: Prismic Palace - Lake Mushroom Cave 1",
"Shroom: Prismic Palace - Observatory Slide 5",
"Shroom: Prismic Palace - Observatory Slide 4",
"Shroom: Prismic Palace - Observatory Slide 3",
"Shroom: Prismic Palace - Observatory Slide 2",
"Shroom: Prismic Palace - Observatory Slide 1",
"Shroom: Prismic Palace - Poki-Poki Cave 1",
"Shroom: Prismic Palace - Poki-Poki Cave 2",
"Shroom: Prismic Palace - Poki-Poki Cave 3",
"Shroom: Prismic Palace - Poki-Poki Cave 4",
"Shroom: Prismic Palace - Poki-Poki Cave 5",
"Shroom: Prismic Palace - Pool 1",
"Shroom: Prismic Palace - Pool 2",
"Shroom: Prismic Palace - Pool 3",
"Shroom: Prismic Palace - Pool 4",
"Shroom: Prismic Palace - Pool 5",
"Shroom: Prismic Palace - Lake Basement Entry 3",
"Shroom: Prismic Palace - Lake Basement Entry 4",
"Shroom: Prismic Palace - Lake Basement Entry 5",
"Shroom: Prismic Palace - Lake Basement Entry 6",
"Shroom: Prismic Palace - Lake Basement Entry 8",
"Shroom: Prismic Palace - Lake Basement Entry 7",
"Shroom: Prismic Palace - Lake Basement Entry 2",
"Shroom: Prismic Palace - Lake Basement Entry 1",
"Shroom: Prismic Palace - Lake Corner 1",
"Shroom: Prismic Palace - Lake Corner 2",
"Shroom: Prismic Palace - Lake Corner 3",
"Shroom: Prismic Palace - Lake Behind 3",
"Shroom: Prismic Palace - Lake Behind 1",
"Shroom: Prismic Palace - Lake Behind 2",
"Shroom: Prismic Palace - Pool Bridges 2",
"Shroom: Prismic Palace - Pool Bridges 3",
"Shroom: Prismic Palace - Pool Bridges 1",
"Shroom: Prismic Palace - Pool Bridges 5",
"Shroom: Prismic Palace - Pool Bridges 4",
"Shroom: Prismic Palace - Pool Bridges 6",
"Shroom: Palace Interior - Star Puzzle 3",
"Shroom: Palace Interior - Star Puzzle 1",
"Shroom: Palace Interior - Star Puzzle 2",
"Shroom: Palace Interior - Heaven's Path Entry 3",
"Shroom: Palace Interior - Heaven's Path Entry 1",
"Shroom: Palace Interior - Heaven's Path Entry 2",
"Shroom: Palace Interior - Bubble Conch Room 3",
"Shroom: Palace Interior - Bubble Conch Room 1",
"Shroom: Palace Interior - Bubble Conch Room 2",
"Shroom: Palace Interior - Sentry Control Chamber 3",
"Shroom: Palace Interior - Sentry Control Chamber 1",
"Shroom: Palace Interior - Sentry Control Chamber 2",
"Shroom: Palace Interior - Palace Back 1",
"Shroom: Palace Interior - Palace Back 2",
"Shroom: Palace Interior - Palace Back 3",
"Shroom: Palace Interior - Palace Back 4",
"Shroom: Palace Interior - Palace Back 5",
"Shroom: Palace Interior - Palace Back 6",
"Shroom: Palace Interior - Bubble Conch Room 4",
"Shroom: Palace Interior - Bubble Conch Room 5",
]
shroomItem: TypeAlias = Literal[
"Cavern Shroom 1",
"Cavern Shroom 2",
"Cavern Shroom 3",
"Cavern Shroom 4",
"Cavern Shroom 5",
"Cavern Shroom 6",
"Cavern Shroom 7",
"Cavern Shroom 8",
"Cavern Shroom 9",
"Cavern Shroom 10",
"Cavern Shroom 11",
"Cavern Shroom 12",
"Cavern Shroom 13",
"Cavern Shroom 14",
"Cavern Shroom 15",
"Cavern Shroom 16",
"Cavern Shroom 17",
"Cavern Shroom 18",
"Cavern Shroom 19",
"Cavern Shroom 20",
"Cavern Shroom 21",
"Cavern Shroom 22",
"Cavern Shroom 23",
"Cavern Shroom 24",
"Cavern Shroom 25",
"Cavern Shroom 26",
"Cavern Shroom 27",
"Cavern Shroom 28",
"Cavern Shroom 29",
"Cavern Shroom 30",
"Cavern Shroom 31",
"Cavern Shroom 32",
"Cavern Shroom 33",
"Cavern Shroom 34",
"Cavern Shroom 35",
"Cavern Shroom 36",
"Cavern Shroom 37",
"Cavern Shroom 38",
"Cavern Shroom 39",
"Cavern Shroom 40",
"Cavern Shroom 41",
"Cavern Shroom 42",
"Cavern Shroom 43",
"Cavern Shroom 44",
"Cavern Shroom 45",
"Cavern Shroom 46",
"Cavern Shroom 47",
"Cavern Shroom 48",
"Cavern Shroom 49",
"Cavern Shroom 50",
"Cavern Shroom 51",
"Cavern Shroom 52",
"Cavern Shroom 53",
"Cavern Shroom 54",
"Cavern Shroom 55",
"Cavern Shroom 56",
"Cavern Shroom 57",
"Cavern Shroom 58",
"Cavern Shroom 59",
"Cavern Shroom 60",
"Cavern Shroom 61",
"Cavern Shroom 62",
"Cavern Shroom 63",
"Cavern Shroom 64",
"Cavern Shroom 65",
"Cavern Shroom 66",
"Cavern Shroom 67",
"Cavern Shroom 68",
"Cavern Shroom 69",
"Cavern Shroom 70",
"Cavern Shroom 71",
"Cavern Shroom 72",
"Cavern Shroom 73",
"Cavern Shroom 74",
"Cavern Shroom 75",
"Cavern Shroom 76",
"Cavern Shroom 77",
"Cavern Shroom 78",
"Cavern Shroom 79",
"Cavern Shroom 80",
"Lostleaf Shroom 1",
"Lostleaf Shroom 2",
"Lostleaf Shroom 3",
"Lostleaf Shroom 4",
"Lostleaf Shroom 5",
"Lostleaf Shroom 6",
"Lostleaf Shroom 7",
"Lostleaf Shroom 8",
"Lostleaf Shroom 9",
"Lostleaf Shroom 10",
"Lostleaf Shroom 11",
"Lostleaf Shroom 12",
"Lostleaf Shroom 13",
"Lostleaf Shroom 14",
"Lostleaf Shroom 15",
"Lostleaf Shroom 16",
"Lostleaf Shroom 17",
"Lostleaf Shroom 18",
"Lostleaf Shroom 19",
"Lostleaf Shroom 20",
"Lostleaf Shroom 21",
"Lostleaf Shroom 22",
"Lostleaf Shroom 23",
"Lostleaf Shroom 24",
"Lostleaf Shroom 25",
"Lostleaf Shroom 26",
"Lostleaf Shroom 27",
"Lostleaf Shroom 28",
"Lostleaf Shroom 29",
"Lostleaf Shroom 30",
"Lostleaf Shroom 31",
"Lostleaf Shroom 32",
"Lostleaf Shroom 33",
"Lostleaf Shroom 34",
"Lostleaf Shroom 35",
"Lostleaf Shroom 36",
"Lostleaf Shroom 37",
"Lostleaf Shroom 38",
"Lostleaf Shroom 39",
"Lostleaf Shroom 40",
"Lostleaf Shroom 41",
"Lostleaf Shroom 42",
"Lostleaf Shroom 43",
"Lostleaf Shroom 44",
"Lostleaf Shroom 45",
"Lostleaf Shroom 46",
"Lostleaf Shroom 47",
"Lostleaf Shroom 48",
"Lostleaf Shroom 49",
"Lostleaf Shroom 50",
"Lostleaf Shroom 51",
"Lostleaf Shroom 52",
"Lostleaf Shroom 53",
"Lostleaf Shroom 54",
"Lostleaf Shroom 55",
"Lostleaf Shroom 56",
"Lostleaf Shroom 57",
"Lostleaf Shroom 58",
"Lostleaf Shroom 59",
"Lostleaf Shroom 60",
"Armada Shroom 1",
"Armada Shroom 2",
"Armada Shroom 3",
"Armada Shroom 4",
"Armada Shroom 5",
"Armada Shroom 6",
"Armada Shroom 7",
"Armada Shroom 8",
"Armada Shroom 9",
"Armada Shroom 10",
"Armada Shroom 11",
"Armada Shroom 12",
"Armada Shroom 13",
"Armada Shroom 14",
"Armada Shroom 15",
"Armada Shroom 16",
"Armada Shroom 17",
"Armada Shroom 18",
"Armada Shroom 19",
"Armada Shroom 20",
"Armada Shroom 21",
"Armada Shroom 22",
"Armada Shroom 23",
"Armada Shroom 24",
"Armada Shroom 25",
"Armada Shroom 26",
"Armada Shroom 27",
"Armada Shroom 28",
"Armada Shroom 29",
"Armada Shroom 30",
"Armada Shroom 31",
"Armada Shroom 32",
"Armada Shroom 33",
"Armada Shroom 34",
"Armada Shroom 35",
"Armada Shroom 36",
"Armada Shroom 37",
"Armada Shroom 38",
"Armada Shroom 39",
"Armada Shroom 40",
"Armada Shroom 41",
"Armada Shroom 42",
"Armada Shroom 43",
"Armada Shroom 44",
"Armada Shroom 45",
"Armada Shroom 46",
"Armada Shroom 47",
"Armada Shroom 48",
"Armada Shroom 49",
"Armada Shroom 50",
"Armada Shroom 51",
"Armada Shroom 52",
"Armada Shroom 53",
"Armada Shroom 54",
"Armada Shroom 55",
"Armada Shroom 56",
"Armada Shroom 57",
"Armada Shroom 58",
"Armada Shroom 59",
"Armada Shroom 60",
"Armada Shroom 61",
"Armada Shroom 62",
"Armada Shroom 63",
"Armada Shroom 64",
"Armada Shroom 65",
"Armada Shroom 66",
"Armada Shroom 67",
"Armada Shroom 68",
"Armada Shroom 69",
"Armada Shroom 70",
"Armada Shroom 71",
"Armada Shroom 72",
"Armada Shroom 73",
"Armada Shroom 74",
"Armada Shroom 75",
"Armada Shroom 76",
"Armada Shroom 77",
"Armada Shroom 78",
"Armada Shroom 79",
"Armada Shroom 80",
"Palace Shroom 1",
"Palace Shroom 2",
"Palace Shroom 3",
"Palace Shroom 4",
"Palace Shroom 5",
"Palace Shroom 6",
"Palace Shroom 7",
"Palace Shroom 8",
"Palace Shroom 9",
"Palace Shroom 10",
"Palace Shroom 11",
"Palace Shroom 12",
"Palace Shroom 13",
"Palace Shroom 14",
"Palace Shroom 15",
"Palace Shroom 16",
"Palace Shroom 17",
"Palace Shroom 18",
"Palace Shroom 19",
"Palace Shroom 20",
"Palace Shroom 21",
"Palace Shroom 22",
"Palace Shroom 23",
"Palace Shroom 24",
"Palace Shroom 25",
"Palace Shroom 26",
"Palace Shroom 27",
"Palace Shroom 28",
"Palace Shroom 29",
"Palace Shroom 30",
"Palace Shroom 31",
"Palace Shroom 32",
"Palace Shroom 33",
"Palace Shroom 34",
"Palace Shroom 35",
"Palace Shroom 36",
"Palace Shroom 37",
"Palace Shroom 38",
"Palace Shroom 39",
"Palace Shroom 40",
"Palace Shroom 41",
"Palace Shroom 42",
"Palace Shroom 43",
"Palace Shroom 44",
"Palace Shroom 45",
"Palace Shroom 46",
"Palace Shroom 47",
"Palace Shroom 48",
"Palace Shroom 49",
"Palace Shroom 50",
"Palace Shroom 51",
"Palace Shroom 52",
"Palace Shroom 53",
"Palace Shroom 54",
"Palace Shroom 55",
"Palace Shroom 56",
"Palace Shroom 57",
"Palace Shroom 58",
"Palace Shroom 59",
"Palace Shroom 60",
"Palace Shroom 61",
"Palace Shroom 62",
"Palace Shroom 63",
"Palace Shroom 64",
"Palace Shroom 65",
"Palace Shroom 66",
"Palace Shroom 67",
"Palace Shroom 68",
"Palace Shroom 69",
"Palace Shroom 70",
"Palace Shroom 71",
"Palace Shroom 72",
"Palace Shroom 73",
"Palace Shroom 74",
"Palace Shroom 75",
"Palace Shroom 76",
"Palace Shroom 77",
"Palace Shroom 78",
"Palace Shroom 79",
"Palace Shroom 80",
"Palace Shroom 81",
"Palace Shroom 82",
"Palace Shroom 83",
"Palace Shroom 84",
"Palace Shroom 85",
"Palace Shroom 86",
"Palace Shroom 87",
"Palace Shroom 88",
"Palace Shroom 89",
"Palace Shroom 90",
"Palace Shroom 91",
"Palace Shroom 92",
"Palace Shroom 93",
"Palace Shroom 94",
"Palace Shroom 95",
"Palace Shroom 96",
"Palace Shroom 97",
"Palace Shroom 98",
"Palace Shroom 99",
"Palace Shroom 100",
]
AnyLocation: TypeAlias = Literal[
"Sun Cavern - Sage's Blessing 1",
"Sun Cavern - Sage's Blessing 2",
"Sun Cavern - Sage's Blessing 3",
"Sun Cavern - Sage's Blessing 4",
"Sun Cavern - Sage's Blessing 5",
"Lostleaf Lake - Treehouse Fish Food",
"Lady Opal's Egg: Castle",
"Lady Opal's Egg: Pool",
"Lady Opal's Egg: Poki-Poki",
"Beat Mighty Wall",
"Moon Cavern Heart Door",
"Armada Lobby Purple Valve",
"Armada Lobby Green Valve",
"Palace Lobby Faucet Preston",
"Palace Lobby Whirlpool Preston",
"Gallery Lobby - Extinguish Torches",
"Gallery Lobby - Hedge Maze Preston",
"Lostleaf Lake - Winky Tree Target",
"Lostleaf Lake - Help Shelnert",
"Lostleaf Lake - Back of the Headstone",
"Lostleaf Lake - Ring Bell",
"Lostleaf Lake - Angel Statue Puzzle",
"Lostleaf Lake - Treehouse Preston",
"Armada Interior - Help Mr. Kerrington",
"Armada Interior - Generators Puzzle",
"Heart - Generators Puzzle",
"Prismic Palace - Basement Star Hoops",
"Palace-Lostleaf Connector - Preston",
"Prismic Palace - Angel Statue Puzzle",
"Prismic Palace - Help Lady Opal",
"Prismic Palace - Snowcastle Preston",
"Prismic Palace - Observatory Preston",
"Palace Interior - Sentry Control Preston",
"Palace Interior - Seastar Puzzle",
"Heaven's Path - Finished Race",
"Heaven's Path - Bottom Preston",
"Palace Dining Room - Preston",
"Gallery of Nightmares - Sage's Painting",
"Gallery of Nightmares - Mr. Kerrington's Painting",
"Gallery of Nightmares - Shelnert's Painting",
"Gallery-Armada Connector - Preston",
"Gallery of Nightmares - Swamp Angel Statue Puzzle",
"Gallery of Nightmares - Sewer Angel Statue Puzzle",
"Gallery of Nightmares - Lady Opal's Painting",
"Gallery of Nightmares - Helped Sniffles",
"Gallery of Nightmares - Fire Lobby Preston",
"Gallery of Nightmares - Fire Lobby Hoops",
"Coils of Agony - Hidden Pillar",
"Card: Sun Cavern - Air Vent",
"Card: Lostleaf Lobby - Branches",
"Card: Moon Cavern - Statue",
"Card: Armada Lobby - Jester Boots",
"Card: Moon Cavern - Dive",
"Card: Gallery Lobby - Hedge Maze",
"Card: Lostleaf Lake - Teepee",
"Card: Lostleaf Lake - Apple Tree",
"Card: Lostleaf Lake - Lake Stump",
"Card: Church - Top",
"Card: Lostleaf Lake - Entry",
"Card: Lostleaf Lake - Treehouse",
"Card: Armada Interior - Slide",
"Card: Armada Interior - Pipe",
"Card: Armada Interior - Broken Wing",
"Card: Airborne Armada - Behind Entry Drone",
"Card: Armada Interior - Hammocks",
"Card: Armada Interior - Near Mr. Kerrington's Heart",
"Card: Prismic Palace - Observatory",
"Card: Prismic Palace - Top of Observatory",
"Card: Prismic Palace - Snowcastle",
"Card: Prismic Palace - Top of Palace",
"Card: Prismic Palace - Above Pool",
"Card: Prismic Palace - Inside Palace",
"Card: Gallery of Nightmares - Swamp Castle",
"Card: Gallery of Nightmares - Sewer Bottom",
"Card: Gallery of Nightmares - Basement Entrance",
"Card: Gallery of Nightmares - Swamp",
"Card: Gallery of Nightmares - Frying Pans",
"Card: Gallery of Nightmares - Above Pits of Despair Painting",
"Card: Sewer - Armada Lobby Side",
"Card: Sewer - Gallery of Nightmares Side",
"Card: Dream",
"Card: Gallery Lobby - Behind the Gallery",
"Card: Palace Dining Room - Top",
"Card: Palace Lobby - Top",
"Egg: Sun Cavern - Mighty Wall",
"Egg: Sun Cavern - Waterfall",
"Egg: Moon Cavern - Dive Puzzle",
"Egg: Moon Cavern - Keehee Climb",
"Egg: Lostleaf Lobby - Branches",
"Egg: Armada Lobby - Cannon",
"Egg: Palace Lobby - Submerged",
"Egg: Gallery Lobby - Lostleaf Lobby Entryway",
"Egg: Lostleaf Lake - Entry Stump",
"Egg: Lostleaf Lake - Jester Boots",
"Egg: Lostleaf Lake - Lake Log",
"Egg: Lostleaf Lake - Waterfall",
"Egg: Crypt - Shelwart's Gravestone",
"Egg: Lostleaf Lake - Deep Woods Puzzle",
"Egg: Lostleaf Lake - Near the Treehouse",
"Egg: Church - Below the Angel Statues",
"Egg: Airborne Armada - Mr. Kerrington's Tail",
"Egg: Fire Drone",
"Egg: Armada Interior - Slide",
"Egg: Armada Interior - Dog Food",
"Egg: Armada Interior - Boiler",
"Egg: Armada Interior - Pipe",
"Egg: Mr. Kerrington's Heart",
"Egg: Armada Interior - Dumpling",
"Egg: Prismic Palace - Snowcastle",
"Egg: Palace Dining Room",
"Egg: Observatory",
"Egg: Prismic Palace - Observatory Slide",
"Egg: Prismic Palace - Bigstar",
"Egg: Prismic Palace - Top of the Palace",
"Egg: Palace Interior - Basement",
"Egg: Prismic Palace - Gobbler",
"Egg: Coils of Agony",
"Egg: Pits of Despair",
"Egg: Wastes of Eternity",
"Egg: Gallery of Nightmares - Matryoshka Egg",
"Egg: Gallery of Nightmares - Skull's Eye",
"Egg: Gallery of Nightmares - Mr. Kerrington Painting",
"Egg: Gallery of Nightmares - Sewer",
"Egg: Gallery of Nightmares - Deepest Darkness",
"Shroom: Sun Cavern - Mighty Wall Ground 1",
"Shroom: Sun Cavern - Mighty Wall Ground 2",
"Shroom: Sun Cavern - Mighty Wall Ground 3",
"Shroom: Sun Cavern - Mighty Wall Ground 4",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 1",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 2",
"Shroom: Sun Cavern - Mighty Wall Egg Ledge 3",
"Shroom: Sun Cavern - High Jump Ledge 1",
"Shroom: Sun Cavern - High Jump Ledge 2",
"Shroom: Sun Cavern - Tail Spin Ledge 1",
"Shroom: Sun Cavern - Tail Spin Ledge 2",
"Shroom: Sun Cavern - Ducklings Ledge 1",
"Shroom: Sun Cavern - Ducklings Ledge 2",
"Shroom: Sun Cavern - Armada Entrance 1",
"Shroom: Sun Cavern - Armada Entrance 2",
"Shroom: Sun Cavern - Armada Entrance 3",
"Shroom: Sun Cavern - Vine Ledge 1",
"Shroom: Sun Cavern - Vine Ledge 2",
"Shroom: Moon Cavern - Dive Holes 1",
"Shroom: Moon Cavern - Dive Holes 2",
"Shroom: Moon Cavern - Dive Holes 3",
"Shroom: Moon Cavern - Dive Holes 4",
"Shroom: Moon Cavern - Dive Holes 5",
"Shroom: Moon Cavern - Dive Holes 6",
"Shroom: Moon Cavern - Dive Puzzle 1",
"Shroom: Moon Cavern - Dive Puzzle 2",
"Shroom: Moon Cavern - Dive Puzzle 3",
"Shroom: Moon Cavern - Potionfall",
"Shroom: Moon Cavern - Lonely Shroom",
"Shroom: Moon Cavern - Palace Lobby Pathway 2",
"Shroom: Moon Cavern - Palace Lobby Pathway 1",
"Shroom: Moon Cavern - Palace Lobby Pathway 3",
"Shroom: Moon Cavern - Palace Lobby Statue 1",
"Shroom: Moon Cavern - Palace Lobby Statue 2",
"Shroom: Moon Cavern - Palace Lobby Entryway 1",
"Shroom: Moon Cavern - Palace Lobby Entryway 2",
"Shroom: Moon Cavern - Palace Lobby Entryway 3",
"Shroom: Moon Cavern - Lava Platforms 1",
"Shroom: Moon Cavern - Lava Platforms 2",
"Shroom: Moon Cavern - Lava Platforms 3",
"Shroom: Moon Cavern - Lava Platforms 4",
"Shroom: Moon Cavern - Lava Mushroom Platform 1",
"Shroom: Moon Cavern - Lava Mushroom Platform 2",
"Shroom: Lostleaf Lobby - Bridge 2",
"Shroom: Lostleaf Lobby - Bridge 3",
"Shroom: Lostleaf Lobby - Bridge 1",
"Shroom: Lostleaf Lobby - Trees 1",
"Shroom: Lostleaf Lobby - Trees 2",
"Shroom: Lostleaf Lobby - Trees 3",
"Shroom: Armada Lobby - Cliffside 1",
"Shroom: Armada Lobby - Cliffside 2",
"Shroom: Armada Lobby - Cliffside 4",
"Shroom: Armada Lobby - Cliffside 5",
"Shroom: Armada Lobby - Cliffside 3",
"Shroom: Palace Lobby - Ledges 1",
"Shroom: Palace Lobby - Ledges 6",
"Shroom: Palace Lobby - Ledges 5",
"Shroom: Palace Lobby - Ledges 3",
"Shroom: Palace Lobby - Ledges 2",
"Shroom: Palace Lobby - Ledges 4",
"Shroom: Palace Lobby - Underwater 1",
"Shroom: Palace Lobby - Underwater 2",
"Shroom: Palace Lobby - Underwater 3",
"Shroom: Palace Lobby - Underwater 5",
"Shroom: Palace Lobby - Underwater 6",
"Shroom: Palace Lobby - Underwater 4",
"Shroom: Gallery Lobby - Fountain 1",
"Shroom: Gallery Lobby - Fountain 2",
"Shroom: Gallery Lobby - Fountain 3",
"Shroom: Gallery Lobby - Fountain 4",
"Shroom: Gallery Lobby - Castle Hill 3",
"Shroom: Gallery Lobby - Castle Hill 5",
"Shroom: Gallery Lobby - Castle Hill 4",
"Shroom: Gallery Lobby - Castle Hill 1",
"Shroom: Gallery Lobby - Castle Hill 2",
"Shroom: Gallery Lobby - Entryway 1",
"Shroom: Gallery Lobby - Entryway 4",
"Shroom: Gallery Lobby - Entryway 5",
"Shroom: Gallery Lobby - Entryway 3",
"Shroom: Gallery Lobby - Entryway 2",
"Shroom: Lostleaf Lake - Treehouse Branches 4",
"Shroom: Lostleaf Lake - Treehouse Branches 3",
"Shroom: Lostleaf Lake - Treehouse Branches 1",
"Shroom: Lostleaf Lake - Treehouse Branches 2",
"Shroom: Lostleaf Lake - Treehouse Branches 6",
"Shroom: Lostleaf Lake - Treehouse Branches 5",
"Shroom: Lostleaf Lake - Deep Woods 2",
"Shroom: Lostleaf Lake - Deep Woods 1",
"Shroom: Lostleaf Lake - Deep Woods 3",
"Shroom: Lostleaf Lake - Deep Woods 6",
"Shroom: Lostleaf Lake - Deep Woods 4",
"Shroom: Lostleaf Lake - Deep Woods 5",
"Shroom: Lostleaf Lake - Behind Church 3",
"Shroom: Lostleaf Lake - Behind Church 1",
"Shroom: Lostleaf Lake - Behind Church 2",
"Shroom: Lostleaf Lake - Teepee 1",
"Shroom: Lostleaf Lake - Teepee 3",
"Shroom: Lostleaf Lake - Teepee 2",
"Shroom: Lostleaf Lake - Waterfall Logs 2",
"Shroom: Lostleaf Lake - Waterfall Logs 3",
"Shroom: Lostleaf Lake - Waterfall Logs 4",
"Shroom: Lostleaf Lake - Waterfall Logs 1",
"Shroom: Lostleaf Lake - Lake Logs 2",
"Shroom: Lostleaf Lake - Lake Logs 1",
"Shroom: Lostleaf Lake - Lake Logs 3",
"Shroom: Lostleaf Lake - Lake Logs 4",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 1",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 2",
"Shroom: Lostleaf Lake - Winky Bouncy Mushroom 3",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 1",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 3",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 5",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 2",
"Shroom: Lostleaf Lake - Ramp to Winky Tree 4",
"Shroom: Lostleaf Lake - Deep Woods Entryway 1",
"Shroom: Lostleaf Lake - Deep Woods Entryway 2",
"Shroom: Lostleaf Lake - Deep Woods Entryway 3",
"Shroom: Lostleaf Lake - Lake Gravestone 1",
"Shroom: Lostleaf Lake - Lake Gravestone 2",
"Shroom: Lostleaf Lake - Lake Gravestone 3",
"Shroom: Lostleaf Lake - Bridge 2",
"Shroom: Lostleaf Lake - Bridge 1",
"Shroom: Lostleaf Lake - Bridge 3",
"Shroom: Lostleaf Lake - Winky Apple Tree 4",
"Shroom: Lostleaf Lake - Winky Apple Tree 3",
"Shroom: Lostleaf Lake - Winky Apple Tree 1",
"Shroom: Lostleaf Lake - Winky Apple Tree 2",
"Shroom: Lostleaf Lake - Church Entryway 3",
"Shroom: Lostleaf Lake - Church Entryway 2",
"Shroom: Lostleaf Lake - Church Entryway 1",
"Shroom: Church - Pews 4",
"Shroom: Church - Pews 2",
"Shroom: Church - Pews 1",
"Shroom: Church - Pews 3",
"Shroom: Treehouse - Corners 4",
"Shroom: Treehouse - Corners 3",
"Shroom: Treehouse - Corners 2",
"Shroom: Treehouse - Corners 1",
"Shroom: Treehouse - Corners 5",
"Shroom: Treehouse - Corners 6",
"Shroom: Airborne Armada - Bouncy Shroom 1",
"Shroom: Airborne Armada - Bouncy Shroom 3",
"Shroom: Airborne Armada - Bouncy Shroom 2",
"Shroom: Airborne Armada - Bouncy Shroom 4",
"Shroom: Airborne Armada - Entry Pathway 5",
"Shroom: Airborne Armada - Front Entrance 1",
"Shroom: Airborne Armada - Front Entrance 2",
"Shroom: Airborne Armada - Front Entrance 3",
"Shroom: Airborne Armada - Side 1",
"Shroom: Airborne Armada - Side 2",
"Shroom: Airborne Armada - Side 3",
"Shroom: Airborne Armada - Back Entrance 1",
"Shroom: Airborne Armada - Back Entrance 2",
"Shroom: Airborne Armada - Back Entrance 3",
"Shroom: Airborne Armada - Back Entrance 4",
"Shroom: Airborne Armada - Back Entrance 6",
"Shroom: Airborne Armada - Back Entrance 5",
"Shroom: Airborne Armada - Topside 1",
"Shroom: Airborne Armada - Topside 2",
"Shroom: Airborne Armada - Topside 3",
"Shroom: Airborne Armada - Entry Pathway 1",
"Shroom: Airborne Armada - Entry Pathway 2",
"Shroom: Airborne Armada - Entry Pathway 3",
"Shroom: Airborne Armada - Entry Pathway 4",
"Shroom: Armada Interior - Rain Entryway 4",
"Shroom: Armada Interior - Rain Entryway 3",
"Shroom: Armada Interior - Rain Entryway 2",
"Shroom: Armada Interior - Hammocks Entryway 2",
"Shroom: Armada Interior - Hammocks Entryway 1",
"Shroom: Armada Interior - Cockpit Entry 3",
"Shroom: Armada Interior - Cockpit Entry 2",
"Shroom: Armada Interior - Cockpit Entry 1",
"Shroom: Armada Interior - Cockpit Entry 6",
"Shroom: Armada Interior - Cockpit Entry 5",
"Shroom: Armada Interior - Cockpit Entry 4",
"Shroom: Armada Interior - Rain Below Medicine 3",
"Shroom: Armada Interior - Rain Below Medicine 2",
"Shroom: Armada Interior - Rain Below Boiler 1",
"Shroom: Armada Interior - Rain Below Boiler 2",
"Shroom: Armada Interior - Rain Below Boiler 3",
"Shroom: Armada Interior - Rain Below Medicine 1",
"Shroom: Armada Interior - Rain Plant Base",
"Shroom: Armada Interior - Rain Plant 1",
"Shroom: Armada Interior - Lab Rain Connector 5",
"Shroom: Armada Interior - Lab Rain Connector 6",
"Shroom: Armada Interior - Lab Rain Connector 4",
"Shroom: Armada Interior - Lab Rain Connector 3",
"Shroom: Armada Interior - Lab Rain Connector 2",
"Shroom: Armada Interior - Lab Rain Connector 1",
"Shroom: Armada Interior - Lab Entryway 4",
"Shroom: Armada Interior - Lab Entryway 3",
"Shroom: Armada Interior - Lab Entryway 2",
"Shroom: Armada Interior - Lab Entryway 1",
"Shroom: Armada Interior - Pipe 5",
"Shroom: Armada Interior - Pipe 4",
"Shroom: Armada Interior - Pipe 3",
"Shroom: Armada Interior - Pipe 2",
"Shroom: Armada Interior - Pipe 1",
"Shroom: Armada Interior - Pipe Ramp 3",
"Shroom: Armada Interior - Pipe Ramp 2",
"Shroom: Armada Interior - Pipe Ramp 1",
"Shroom: Armada Interior - Rain Entryway 1",
"Shroom: Armada Interior - Slide Entryway 1",
"Shroom: Armada Interior - Slide Entryway 2",
"Shroom: Armada Interior - Slide Entryway 3",
"Shroom: Armada Interior - Rain Plant 2",
"Shroom: Armada Interior - Rain Plant 3",
"Shroom: Armada Interior - Rain Plant 4",
"Shroom: Armada Interior - Rain Above Boiler 4",
"Shroom: Armada Interior - Rain Above Boiler 2",
"Shroom: Armada Interior - Rain Above Boiler 1",
"Shroom: Armada Interior - Rain Above Boiler 3",
"Shroom: Armada Entry Drone - Ledges 6",
"Shroom: Armada Entry Drone - Ledges 5",
"Shroom: Armada Entry Drone - Ledges 4",
"Shroom: Armada Entry Drone - Ledges 3",
"Shroom: Armada Entry Drone - Ledges 7",
"Shroom: Armada Entry Drone - Ledges 8",
"Shroom: Armada Entry Drone - Ledges 1",
"Shroom: Armada Entry Drone - Ledges 2",
"Shroom: Prismic Palace - Poms 5",
"Shroom: Prismic Palace - Poms 3",
"Shroom: Prismic Palace - Poms 4",
"Shroom: Prismic Palace - Poms 2",
"Shroom: Prismic Palace - Poms 1",
"Shroom: Prismic Palace - Entry Tree 2",
"Shroom: Prismic Palace - Entry Tree 1",
"Shroom: Prismic Palace - Entry Tree 3",
"Shroom: Prismic Palace - Entry 1",
"Shroom: Prismic Palace - Entry 2",
"Shroom: Prismic Palace - Entry 3",
"Shroom: Prismic Palace - Jester Boots 1",
"Shroom: Prismic Palace - Jester Boots 2",
"Shroom: Prismic Palace - Jester Boots 3",
"Shroom: Prismic Palace - Jester Boots 4",
"Shroom: Prismic Palace - Jester Boots 5",
"Shroom: Prismic Palace - Pom Spire 1",
"Shroom: Prismic Palace - Pom Spire 2",
"Shroom: Prismic Palace - Pom Spire 3",
"Shroom: Prismic Palace - Pom Spire 4",
"Shroom: Prismic Palace - Pom Spire 5",
"Shroom: Prismic Palace - Observatory Spire 1",
"Shroom: Prismic Palace - Observatory Spire 2",
"Shroom: Prismic Palace - Observatory Spire 3",
"Shroom: Prismic Palace - Observatory Spire 4",
"Shroom: Prismic Palace - Observatory Spire 5",
"Shroom: Prismic Palace - Lake Gobbler 2",
"Shroom: Prismic Palace - Lake Gobbler 3",
"Shroom: Prismic Palace - Lake Gobbler 1",
"Shroom: Prismic Palace - Lake Plants 2",
"Shroom: Prismic Palace - Lake Plants 3",
"Shroom: Prismic Palace - Lake Plants 1",
"Shroom: Prismic Palace - Lake Plants 5",
"Shroom: Prismic Palace - Lake Plants 6",
"Shroom: Prismic Palace - Lake Plants 4",
"Shroom: Prismic Palace - Lake Basement Overpass 3",
"Shroom: Prismic Palace - Lake Basement Overpass 4",
"Shroom: Prismic Palace - Lake Basement Overpass 5",
"Shroom: Prismic Palace - Lake Basement Overpass 2",
"Shroom: Prismic Palace - Lake Basement Overpass 1",
"Shroom: Prismic Palace - Lake Mushroom Cave 3",
"Shroom: Prismic Palace - Lake Mushroom Cave 4",
"Shroom: Prismic Palace - Lake Mushroom Cave 5",
"Shroom: Prismic Palace - Lake Mushroom Cave 2",
"Shroom: Prismic Palace - Lake Mushroom Cave 1",
"Shroom: Prismic Palace - Observatory Slide 5",
"Shroom: Prismic Palace - Observatory Slide 4",
"Shroom: Prismic Palace - Observatory Slide 3",
"Shroom: Prismic Palace - Observatory Slide 2",
"Shroom: Prismic Palace - Observatory Slide 1",
"Shroom: Prismic Palace - Poki-Poki Cave 1",
"Shroom: Prismic Palace - Poki-Poki Cave 2",
"Shroom: Prismic Palace - Poki-Poki Cave 3",
"Shroom: Prismic Palace - Poki-Poki Cave 4",
"Shroom: Prismic Palace - Poki-Poki Cave 5",
"Shroom: Prismic Palace - Pool 1",
"Shroom: Prismic Palace - Pool 2",
"Shroom: Prismic Palace - Pool 3",
"Shroom: Prismic Palace - Pool 4",
"Shroom: Prismic Palace - Pool 5",
"Shroom: Prismic Palace - Lake Basement Entry 3",
"Shroom: Prismic Palace - Lake Basement Entry 4",
"Shroom: Prismic Palace - Lake Basement Entry 5",
"Shroom: Prismic Palace - Lake Basement Entry 6",
"Shroom: Prismic Palace - Lake Basement Entry 8",
"Shroom: Prismic Palace - Lake Basement Entry 7",
"Shroom: Prismic Palace - Lake Basement Entry 2",
"Shroom: Prismic Palace - Lake Basement Entry 1",
"Shroom: Prismic Palace - Lake Corner 1",
"Shroom: Prismic Palace - Lake Corner 2",
"Shroom: Prismic Palace - Lake Corner 3",
"Shroom: Prismic Palace - Lake Behind 3",
"Shroom: Prismic Palace - Lake Behind 1",
"Shroom: Prismic Palace - Lake Behind 2",
"Shroom: Prismic Palace - Pool Bridges 2",
"Shroom: Prismic Palace - Pool Bridges 3",
"Shroom: Prismic Palace - Pool Bridges 1",
"Shroom: Prismic Palace - Pool Bridges 5",
"Shroom: Prismic Palace - Pool Bridges 4",
"Shroom: Prismic Palace - Pool Bridges 6",
"Shroom: Palace Interior - Star Puzzle 3",
"Shroom: Palace Interior - Star Puzzle 1",
"Shroom: Palace Interior - Star Puzzle 2",
"Shroom: Palace Interior - Heaven's Path Entry 3",
"Shroom: Palace Interior - Heaven's Path Entry 1",
"Shroom: Palace Interior - Heaven's Path Entry 2",
"Shroom: Palace Interior - Bubble Conch Room 3",
"Shroom: Palace Interior - Bubble Conch Room 1",
"Shroom: Palace Interior - Bubble Conch Room 2",
"Shroom: Palace Interior - Sentry Control Chamber 3",
"Shroom: Palace Interior - Sentry Control Chamber 1",
"Shroom: Palace Interior - Sentry Control Chamber 2",
"Shroom: Palace Interior - Palace Back 1",
"Shroom: Palace Interior - Palace Back 2",
"Shroom: Palace Interior - Palace Back 3",
"Shroom: Palace Interior - Palace Back 4",
"Shroom: Palace Interior - Palace Back 5",
"Shroom: Palace Interior - Palace Back 6",
"Shroom: Palace Interior - Bubble Conch Room 4",
"Shroom: Palace Interior - Bubble Conch Room 5",
]
AnyItem: TypeAlias = Literal[
"Tail",
"Horn",
"Wings",
"Bubble",
"Flight",
"Grounded Tail",
"Aerial Tail",
"Double Jump",
"Roll",
"Swim",
"Carry",
"Climb",
"High Jump",
"Sprint",
"Super Jumps",
"Air Swim",
"Fish Food",
"Lady Opal's Egg 1",
"Lady Opal's Egg 2",
"Lady Opal's Egg 3",
"Mighty Wall Toppled",
"Open Moon Cavern Heart Door",
"Armada Lobby Pipes Risen",
"Armada Lobby Red Pipe Updraft",
"Palace Lobby Faucet Running",
"Palace Lobby Whirlpool Active",
"Open Gallery Lobby Hedge Maze",
"Open Gallery Lobby Door",
"Raise Lake Swings",
"Open Deep Woods",
"Open Crypt",
"Open Church",
"Open Church Egg",
"Open Treehouse",
"Open Armada Cockpit",
"Free Armada Buddies",
"Unclog Kerrington's Heart",
"Open Prismic Palace Basement",
"Open Palace-Lostleaf Connector",
"Open Prismic Palace Gate",
"Unfreeze Prismic Palace",
"Open Prismic Palace Snowcastle",
"Open Observatory Shortcut",
"Disable Prismic Palace Seedragons",
"Open Bubble Conch Room",
"Open Heaven's Path Exit",
"Open Heaven's Path Race Entrance",
"Raise Dining Room Platform",
"Open Gallery Doors",
"Open Mr. Kerrington Painting Gate",
"Open Skull's Diamond Eye",
"Open Gallery-Armada Connector",
"Open Gallery of Nightmares Swamp Door",
"Open Gallery of Nightmares Sewer Chest #1",
"Open Gallery of Nightmares Sewer Chest #2",
"Open Luna's House",
"Extend Fire Lobby Tongue Platform",
"Extend Fire Lobby Frying Pans",
"Coils of Agony - Open Snake's Mouth",
"Card: Shroom",
"Card: Mighty Wall",
"Card: Pale Carpy",
"Card: Preston",
"Card: Keehee",
"Card: Hunger",
"Card: Shelnert",
"Card: Shelwart",
"Card: Carpy",
"Card: Raay",
"Card: Sappleing",
"Card: Gabby Grove",
"Card: Mr. Kerrington",
"Card: Skritch",
"Card: Boiby",
"Card: Dumpling",
"Card: F.I.S.H",
"Card: Reaper",
"Card: Lady Opal",
"Card: Poki-Poki",
"Card: Pom",
"Card: Bigstar",
"Card: The Gobbler!",
"Card: Seedragon",
"Card: Rattles",
"Card: Sniffles",
"Card: Starving Art",
"Card: Eternal",
"Card: Heartburn",
"Card: Hawhaw",
"Card: Fynn",
"Card: Fynn's Siblings",
"Card: Sage",
"Card: Luna",
"Card: Boxed Nightmare",
"Card: Frozen King",
"Sun Egg",
"Green Starry Egg",
"Blue Moon Egg",
"Blorange Striped Egg",
"Blue Dotted Egg",
"American Egg",
"Red Swirly Egg",
"Ghost Egg",
"Hatchable Egg: Lostleaf Lake",
"Easter Zig-zag Egg",
"Apple Egg",
"Snowfall Egg",
"Fishbones Egg",
"Sunshine Egg",
"Birds Egg",
"Stained Glass Egg",
"Hatchable Egg: Airborne Armada",
"Burning Egg",
"Bat Egg",
"Doggy Egg",
"Spooky Egg",
"Smiley Egg",
"Heart Egg",
"Dumpling Egg",
"Hatchable Egg: Prismic Palace",
"Ornate Egg",
"Starlit Egg",
"Checkered Egg",
"Flower Egg",
"Snowstorm Egg",
"Zig-zag Egg",
"Happy Egg",
"Red Eyes Egg",
"Seaweed Egg",
"Moonlight Egg",
"Hatchable Egg: Gallery of Nightmares",
"Ripped Egg",
"Robot Egg",
"Bricked Egg",
"Ghost Egg",
"Cavern Shroom 1",
"Cavern Shroom 2",
"Cavern Shroom 3",
"Cavern Shroom 4",
"Cavern Shroom 5",
"Cavern Shroom 6",
"Cavern Shroom 7",
"Cavern Shroom 8",
"Cavern Shroom 9",
"Cavern Shroom 10",
"Cavern Shroom 11",
"Cavern Shroom 12",
"Cavern Shroom 13",
"Cavern Shroom 14",
"Cavern Shroom 15",
"Cavern Shroom 16",
"Cavern Shroom 17",
"Cavern Shroom 18",
"Cavern Shroom 19",
"Cavern Shroom 20",
"Cavern Shroom 21",
"Cavern Shroom 22",
"Cavern Shroom 23",
"Cavern Shroom 24",
"Cavern Shroom 25",
"Cavern Shroom 26",
"Cavern Shroom 27",
"Cavern Shroom 28",
"Cavern Shroom 29",
"Cavern Shroom 30",
"Cavern Shroom 31",
"Cavern Shroom 32",
"Cavern Shroom 33",
"Cavern Shroom 34",
"Cavern Shroom 35",
"Cavern Shroom 36",
"Cavern Shroom 37",
"Cavern Shroom 38",
"Cavern Shroom 39",
"Cavern Shroom 40",
"Cavern Shroom 41",
"Cavern Shroom 42",
"Cavern Shroom 43",
"Cavern Shroom 44",
"Cavern Shroom 45",
"Cavern Shroom 46",
"Cavern Shroom 47",
"Cavern Shroom 48",
"Cavern Shroom 49",
"Cavern Shroom 50",
"Cavern Shroom 51",
"Cavern Shroom 52",
"Cavern Shroom 53",
"Cavern Shroom 54",
"Cavern Shroom 55",
"Cavern Shroom 56",
"Cavern Shroom 57",
"Cavern Shroom 58",
"Cavern Shroom 59",
"Cavern Shroom 60",
"Cavern Shroom 61",
"Cavern Shroom 62",
"Cavern Shroom 63",
"Cavern Shroom 64",
"Cavern Shroom 65",
"Cavern Shroom 66",
"Cavern Shroom 67",
"Cavern Shroom 68",
"Cavern Shroom 69",
"Cavern Shroom 70",
"Cavern Shroom 71",
"Cavern Shroom 72",
"Cavern Shroom 73",
"Cavern Shroom 74",
"Cavern Shroom 75",
"Cavern Shroom 76",
"Cavern Shroom 77",
"Cavern Shroom 78",
"Cavern Shroom 79",
"Cavern Shroom 80",
"Lostleaf Shroom 1",
"Lostleaf Shroom 2",
"Lostleaf Shroom 3",
"Lostleaf Shroom 4",
"Lostleaf Shroom 5",
"Lostleaf Shroom 6",
"Lostleaf Shroom 7",
"Lostleaf Shroom 8",
"Lostleaf Shroom 9",
"Lostleaf Shroom 10",
"Lostleaf Shroom 11",
"Lostleaf Shroom 12",
"Lostleaf Shroom 13",
"Lostleaf Shroom 14",
"Lostleaf Shroom 15",
"Lostleaf Shroom 16",
"Lostleaf Shroom 17",
"Lostleaf Shroom 18",
"Lostleaf Shroom 19",
"Lostleaf Shroom 20",
"Lostleaf Shroom 21",
"Lostleaf Shroom 22",
"Lostleaf Shroom 23",
"Lostleaf Shroom 24",
"Lostleaf Shroom 25",
"Lostleaf Shroom 26",
"Lostleaf Shroom 27",
"Lostleaf Shroom 28",
"Lostleaf Shroom 29",
"Lostleaf Shroom 30",
"Lostleaf Shroom 31",
"Lostleaf Shroom 32",
"Lostleaf Shroom 33",
"Lostleaf Shroom 34",
"Lostleaf Shroom 35",
"Lostleaf Shroom 36",
"Lostleaf Shroom 37",
"Lostleaf Shroom 38",
"Lostleaf Shroom 39",
"Lostleaf Shroom 40",
"Lostleaf Shroom 41",
"Lostleaf Shroom 42",
"Lostleaf Shroom 43",
"Lostleaf Shroom 44",
"Lostleaf Shroom 45",
"Lostleaf Shroom 46",
"Lostleaf Shroom 47",
"Lostleaf Shroom 48",
"Lostleaf Shroom 49",
"Lostleaf Shroom 50",
"Lostleaf Shroom 51",
"Lostleaf Shroom 52",
"Lostleaf Shroom 53",
"Lostleaf Shroom 54",
"Lostleaf Shroom 55",
"Lostleaf Shroom 56",
"Lostleaf Shroom 57",
"Lostleaf Shroom 58",
"Lostleaf Shroom 59",
"Lostleaf Shroom 60",
"Armada Shroom 1",
"Armada Shroom 2",
"Armada Shroom 3",
"Armada Shroom 4",
"Armada Shroom 5",
"Armada Shroom 6",
"Armada Shroom 7",
"Armada Shroom 8",
"Armada Shroom 9",
"Armada Shroom 10",
"Armada Shroom 11",
"Armada Shroom 12",
"Armada Shroom 13",
"Armada Shroom 14",
"Armada Shroom 15",
"Armada Shroom 16",
"Armada Shroom 17",
"Armada Shroom 18",
"Armada Shroom 19",
"Armada Shroom 20",
"Armada Shroom 21",
"Armada Shroom 22",
"Armada Shroom 23",
"Armada Shroom 24",
"Armada Shroom 25",
"Armada Shroom 26",
"Armada Shroom 27",
"Armada Shroom 28",
"Armada Shroom 29",
"Armada Shroom 30",
"Armada Shroom 31",
"Armada Shroom 32",
"Armada Shroom 33",
"Armada Shroom 34",
"Armada Shroom 35",
"Armada Shroom 36",
"Armada Shroom 37",
"Armada Shroom 38",
"Armada Shroom 39",
"Armada Shroom 40",
"Armada Shroom 41",
"Armada Shroom 42",
"Armada Shroom 43",
"Armada Shroom 44",
"Armada Shroom 45",
"Armada Shroom 46",
"Armada Shroom 47",
"Armada Shroom 48",
"Armada Shroom 49",
"Armada Shroom 50",
"Armada Shroom 51",
"Armada Shroom 52",
"Armada Shroom 53",
"Armada Shroom 54",
"Armada Shroom 55",
"Armada Shroom 56",
"Armada Shroom 57",
"Armada Shroom 58",
"Armada Shroom 59",
"Armada Shroom 60",
"Armada Shroom 61",
"Armada Shroom 62",
"Armada Shroom 63",
"Armada Shroom 64",
"Armada Shroom 65",
"Armada Shroom 66",
"Armada Shroom 67",
"Armada Shroom 68",
"Armada Shroom 69",
"Armada Shroom 70",
"Armada Shroom 71",
"Armada Shroom 72",
"Armada Shroom 73",
"Armada Shroom 74",
"Armada Shroom 75",
"Armada Shroom 76",
"Armada Shroom 77",
"Armada Shroom 78",
"Armada Shroom 79",
"Armada Shroom 80",
"Palace Shroom 1",
"Palace Shroom 2",
"Palace Shroom 3",
"Palace Shroom 4",
"Palace Shroom 5",
"Palace Shroom 6",
"Palace Shroom 7",
"Palace Shroom 8",
"Palace Shroom 9",
"Palace Shroom 10",
"Palace Shroom 11",
"Palace Shroom 12",
"Palace Shroom 13",
"Palace Shroom 14",
"Palace Shroom 15",
"Palace Shroom 16",
"Palace Shroom 17",
"Palace Shroom 18",
"Palace Shroom 19",
"Palace Shroom 20",
"Palace Shroom 21",
"Palace Shroom 22",
"Palace Shroom 23",
"Palace Shroom 24",
"Palace Shroom 25",
"Palace Shroom 26",
"Palace Shroom 27",
"Palace Shroom 28",
"Palace Shroom 29",
"Palace Shroom 30",
"Palace Shroom 31",
"Palace Shroom 32",
"Palace Shroom 33",
"Palace Shroom 34",
"Palace Shroom 35",
"Palace Shroom 36",
"Palace Shroom 37",
"Palace Shroom 38",
"Palace Shroom 39",
"Palace Shroom 40",
"Palace Shroom 41",
"Palace Shroom 42",
"Palace Shroom 43",
"Palace Shroom 44",
"Palace Shroom 45",
"Palace Shroom 46",
"Palace Shroom 47",
"Palace Shroom 48",
"Palace Shroom 49",
"Palace Shroom 50",
"Palace Shroom 51",
"Palace Shroom 52",
"Palace Shroom 53",
"Palace Shroom 54",
"Palace Shroom 55",
"Palace Shroom 56",
"Palace Shroom 57",
"Palace Shroom 58",
"Palace Shroom 59",
"Palace Shroom 60",
"Palace Shroom 61",
"Palace Shroom 62",
"Palace Shroom 63",
"Palace Shroom 64",
"Palace Shroom 65",
"Palace Shroom 66",
"Palace Shroom 67",
"Palace Shroom 68",
"Palace Shroom 69",
"Palace Shroom 70",
"Palace Shroom 71",
"Palace Shroom 72",
"Palace Shroom 73",
"Palace Shroom 74",
"Palace Shroom 75",
"Palace Shroom 76",
"Palace Shroom 77",
"Palace Shroom 78",
"Palace Shroom 79",
"Palace Shroom 80",
"Palace Shroom 81",
"Palace Shroom 82",
"Palace Shroom 83",
"Palace Shroom 84",
"Palace Shroom 85",
"Palace Shroom 86",
"Palace Shroom 87",
"Palace Shroom 88",
"Palace Shroom 89",
"Palace Shroom 90",
"Palace Shroom 91",
"Palace Shroom 92",
"Palace Shroom 93",
"Palace Shroom 94",
"Palace Shroom 95",
"Palace Shroom 96",
"Palace Shroom 97",
"Palace Shroom 98",
"Palace Shroom 99",
"Palace Shroom 100",
]